name: Deploy React App to EC2

on:
  push:
    branches:
      - main  # Change if your deployment branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/*"             # ✅ Sends only the contents of dist/
          target: "/var/www/html"      # ✅ This is where Nginx serves files from
          rm:  false                # ✅ Clean up after upload
          strip_components: 1          # ✅ Avoid nesting dist/ in target
